spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/doc_management_system
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true